### ISSUE TITLE
I want to train your code with my custom data

### ISSUE THREAD

**Issue by Min-Hyuk98** [mikeqzy/3dgs-avatar-release#11]
Hello, I'm interested in your research.
I want to try your code with my custom dataset.
As you mentioned, I was trying to follow the way of Arah, but, 
https://github.com/taconite/arah-release/issues/6
above link says  "For multi-view capture, I think you need to follow neural body and easymocap guidelines".
Can I ask if you followed this instrucrtion, or used openpose, SPIN, MODNet?

**Comment by mikeqzy** [comment]
Hi, thank you for your interest. I did not test on custom dataset myself, but since I'm using the same data format with ARAH, following their guideline should work.

I think it depends on your data capture setup to choose which method to use. If your custom dataset is captured in a calibrated lab setting then you can follow NeuralBody guidelines, otherwise for casual capture you can run off-the-shelf regressors on the video. Hope it helps

**Comment by rorrewang** [comment]
Hello, I really want to run the monocular video I shot or downloaded from the Internet on your project, but I have encountered great difficulties in converting the data set into an acceptable format for the project, and the required parameters are too many and difficult to understand. Could you give me some suggestions on how to convert the following data set into an operational form? I use the PARE（ https://github.com/mkocabas/PARE ） method, and I can get the following results for monocular video input:
pred_cam (n_frames, 3)          # weak perspective camera parameters in cropped image space (s,tx,ty)
orig_cam (n_frames, 4)          # weak perspective camera parameters in original image space (sx,sy,tx,ty)
verts (n_frames, 6890, 3)       # SMPL mesh vertices
pose (n_frames, 72)             # SMPL pose parameters
betas (n_frames, 10)            # SMPL body shape parameters
joints3d (n_frames, 49, 3)      # SMPL 3D joints
joints2d (n_frames, 21, 3)      # 2D keypoint detections by STAF if pose tracking enabled otherwise None
bboxes (n_frames, 4)            # bbox detections (cx,cy,w,h)
frame_ids (n_frames,)           # frame ids in which subject with tracking id #1 appears
smpl_joints2d (n_frames, 49, 2) # SMPL 2D joints
I wonder if these parameters meet the needs of the project. If it can be transformed smoothly, it may become a stable Pipeline to generate custom datasets？Thank you :)

**Comment by rorrewang** [comment]
Especially the camera parameters, I don't know how to get the K D R T of the camera parameters correctly. My custom dataset can be regarded as obtained by a monocular static camera. Can these parameters be calculated by the above data?

**Comment by frankkim1108** [comment]
Hi, @rorrewang 
I'm currently trying to test this model with my custom datasets, and also having great difficulties.
I also have monocluar video data just like you. So, I have some questions on, how you are trying to run this model. 
1. Did you create your own data loader for you dataset?
2. It seems like you have to create your own config.yaml file for you own dataset. Did you create one?
3. How are you going to make it work by using an independent preprocessing method so that goes well with this model?
 
Thank you for your time.... I'm trying to preprocess with [InstantAvatar](https://github.com/tijiang13/InstantAvatar) and make it work with this model...

**Comment by rorrewang** [comment]
> Hi, @rorrewang I'm currently trying to test this model with my custom datasets, and also having great difficulties. I also have monocluar video data just like you. So, I have some questions on, how you are trying to run this model.
> 
> 1. Did you create your own data loader for you dataset?
> 2. It seems like you have to create your own config.yaml file for you own dataset. Did you create one?
> 3. How are you going to make it work by using an independent preprocessing method so that goes well with this model?
> 
> Thank you for your time.... I'm trying to preprocess with [InstantAvatar](https://github.com/tijiang13/InstantAvatar) and make it work with this model...

I'm glad to know that our tasks seem very close. I'd like to help you, but I haven't found a stable method at present. If it goes well, I'll tell you how to run it, or wait for author to give us some suggestions ... @mikeqzy

**Comment by yahui-lee** [comment]
> Hello, I really want to run the monocular video I shot or downloaded from the Internet on your project, but I have encountered great difficulties in converting the data set into an acceptable format for the project, and the required parameters are too many and difficult to understand. Could you give me some suggestions on how to convert the following data set into an operational form? I use the PARE（ https://github.com/mkocabas/PARE ） method, and I can get the following results for monocular video input: pred_cam (n_frames, 3) # weak perspective camera parameters in cropped image space (s,tx,ty) orig_cam (n_frames, 4) # weak perspective camera parameters in original image space (sx,sy,tx,ty) verts (n_frames, 6890, 3) # SMPL mesh vertices pose (n_frames, 72) # SMPL pose parameters betas (n_frames, 10) # SMPL body shape parameters joints3d (n_frames, 49, 3) # SMPL 3D joints joints2d (n_frames, 21, 3) # 2D keypoint detections by STAF if pose tracking enabled otherwise None bboxes (n_frames, 4) # bbox detections (cx,cy,w,h) frame_ids (n_frames,) # frame ids in which subject with tracking id #1 appears smpl_joints2d (n_frames, 49, 2) # SMPL 2D joints I wonder if these parameters meet the needs of the project. If it can be transformed smoothly, it may become a stable Pipeline to generate custom datasets？Thank you :)


Hi, I am very pleased to see someone doing the same work as me, and currently I am also working hard to implement this project using my own dataset. Below is the result I obtained from reading the .npz file of the preprocessed ZJUMoCap dataset for each frame. I hope this can be helpful to you. Also, I hope you can contact me after making some progress. Thank you for your help

- minimal_shape (6890, 3)
- betas (1, 10)
- Jtr_posed (24, 3)
- bone_transforms (24, 4, 4)
- trans (3,)
- root_orient (3,)
- pose_body (63,)
- pose_hand (6,)

**Comment by mikeqzy** [comment]
> Hello, I really want to run the monocular video I shot or downloaded from the Internet on your project, but I have encountered great difficulties in converting the data set into an acceptable format for the project, and the required parameters are too many and difficult to understand. Could you give me some suggestions on how to convert the following data set into an operational form? I use the PARE（ https://github.com/mkocabas/PARE ） method, and I can get the following results for monocular video input: pred_cam (n_frames, 3) # weak perspective camera parameters in cropped image space (s,tx,ty) orig_cam (n_frames, 4) # weak perspective camera parameters in original image space (sx,sy,tx,ty) verts (n_frames, 6890, 3) # SMPL mesh vertices pose (n_frames, 72) # SMPL pose parameters betas (n_frames, 10) # SMPL body shape parameters joints3d (n_frames, 49, 3) # SMPL 3D joints joints2d (n_frames, 21, 3) # 2D keypoint detections by STAF if pose tracking enabled otherwise None bboxes (n_frames, 4) # bbox detections (cx,cy,w,h) frame_ids (n_frames,) # frame ids in which subject with tracking id #1 appears smpl_joints2d (n_frames, 49, 2) # SMPL 2D joints I wonder if these parameters meet the needs of the project. If it can be transformed smoothly, it may become a stable Pipeline to generate custom datasets？Thank you :)

Hi @rorrewang ,
I'm not familiar with the output format of PARE, but here's my guess for the camera parameter:
* You can derive the intrinsic matrix `K` from `orig_cam`
* The distortion matrix `D` should be set as all-zeros
* The extrinsics `R` is identity matrix and `T` is zero

You can run some check by projecting the SMPL vertices onto the image plane with the camera parameters above and see if it aligns with the image.

Besides, I think you'll also need foreground masks for the human, possibly with [MODNet](https://github.com/ZHKKKe/MODNet).

**Comment by jiangguangan** [comment]
请问现在有应用自己数据集的方法了吗

**Comment by jiangguangan** [comment]
Is there a way to handle your own dataset at the moment?

**Comment by yashgarg98** [comment]
Hi @rorrewang , @mikeqzy , I'm trying to test this method on my self-capture videos from different angles. Were you able to train the human on self-capture videos? If so, let me know how you preprocessed the videos.

**Comment by xiyichen** [comment]
I have been able to train the method on custom videos. Given a self-captured video, you can follow these steps:
1. run [SAMv2](https://github.com/facebookresearch/segment-anything-2) to get segmentation masks.
2. run [mmhuman3D](https://github.com/open-mmlab/mmhuman3d) to get SMPL meshes. The method I used is PARE.
3. preprocess the results from step 2 into ARAH formats.
4. modify the config files and train 3dgs-avatar.

You can refer to my scripts for step [1](https://github.com/xiyichen/mmhuman3d/blob/main/get_masks.py), [2](https://github.com/xiyichen/mmhuman3d/blob/main/pare.sh), [3](https://github.com/xiyichen/mmhuman3d/blob/main/prepare_3dgs_avatar.py) and change the data directories and prompt points of the first frame (in step 1) accordingly.
Hope it helps.

**Comment by mikeqzy** [comment]
> I have been able to train the method on custom videos. Given a self-captured video, you can follow these steps:
> 
> 1. run [SAMv2](https://github.com/facebookresearch/segment-anything-2) to get segmentation masks.
> 2. run [mmhuman3D](https://github.com/open-mmlab/mmhuman3d) to get SMPL meshes. The method I used is PARE.
> 3. preprocess the results from step 2 into ARAH formats.
> 4. modify the config files and train 3dgs-avatar.
> 
> You can refer to my scripts for step [1](https://github.com/xiyichen/mmhuman3d/blob/main/get_masks.py), [2](https://github.com/xiyichen/mmhuman3d/blob/main/pare.sh), [3](https://github.com/xiyichen/mmhuman3d/blob/main/prepare_3dgs_avatar.py) and change the data directories and prompt points of the first frame (in step 1) accordingly. Hope it helps.

Thank you Xiyi for providing the scripts!

**Comment by wtpro** [comment]
> I have been able to train the method on custom videos. Given a self-captured video, you can follow these steps:
> 
> 1. run [SAMv2](https://github.com/facebookresearch/segment-anything-2) to get segmentation masks.
> 2. run [mmhuman3D](https://github.com/open-mmlab/mmhuman3d) to get SMPL meshes. The method I used is PARE.
> 3. preprocess the results from step 2 into ARAH formats.
> 4. modify the config files and train 3dgs-avatar.
> 
> You can refer to my scripts for step [1](https://github.com/xiyichen/mmhuman3d/blob/main/get_masks.py), [2](https://github.com/xiyichen/mmhuman3d/blob/main/pare.sh), [3](https://github.com/xiyichen/mmhuman3d/blob/main/prepare_3dgs_avatar.py) and change the data directories and prompt points of the first frame (in step 1) accordingly. Hope it helps.

Hi, @xiyichen 

Thanks for the code! I have successfully run the first 3 steps but I have been stuck on step 4. Could you provide a sample config files for the preprocessed data generated by your code?
