### ISSUE TITLE
Error executing job with overrides: ['dataset=ps_female_3', 'option=iter30k', 'pose_correction=none']

### ISSUE THREAD

**Issue by Mr-ind1fferent** [mikeqzy/3dgs-avatar-release#16]
Thanks for your great work！

When i use python train.py dataset=ps_female_3 option=iter30k pose_correction=none 

There is something wrong and i don't know how to fix it.

![image](https://github.com/mikeqzy/3dgs-avatar-release/assets/74087260/6efcdfb0-0a32-4dcb-a22e-b0e6dd838294)

**Comment by jiangguangan** [comment]
我也遇到了这个问题，不知道你是否解决了

**Comment by Mr-ind1fferent** [comment]
> 我也遇到了这个问题，不知道你是否解决了

最近没在跑这个数据集

**Comment by jiangguangan** [comment]
您最终用的哪个数据集跑通的程序，我也试一试，您认为是数据集的问题还是说预处理有问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mikeqzy/3dgs-avatar-release"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月9日(星期四) 晚上7:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mikeqzy/3dgs-avatar-release] Error executing job with overrides: ['dataset=ps_female_3', 'option=iter30k', 'pose_correction=none'] (Issue #16)





  
我也遇到了这个问题，不知道你是否解决了
  
最近没在跑这个数据集

**Comment by Mr-ind1fferent** [comment]
> 您最终用的哪个数据集跑通的程序，我也试一试，您认为是数据集的问题还是说预处理有问题
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "mikeqzy/3dgs-avatar-release" ***@***.***&gt;; 发送时间:&nbsp;2024年5月9日(星期四) 晚上7:36 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [mikeqzy/3dgs-avatar-release] Error executing job with overrides: ['dataset=ps_female_3', 'option=iter30k', 'pose_correction=none'] (Issue #16) 我也遇到了这个问题，不知道你是否解决了 最近没在跑这个数据集 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

最近都在跑zju那个数据集，这个是没问题的。

**Comment by jiangguangan** [comment]
那不知道您是否有预处理好的数据集，不知道可不可以发我一份，如果可以的话，可以有偿，无论如何都感谢您的回答




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mikeqzy/3dgs-avatar-release"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月9日(星期四) 晚上7:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mikeqzy/3dgs-avatar-release] Error executing job with overrides: ['dataset=ps_female_3', 'option=iter30k', 'pose_correction=none'] (Issue #16)





  
您最终用的哪个数据集跑通的程序，我也试一试，您认为是数据集的问题还是说预处理有问题
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "mikeqzy/3dgs-avatar-release" @.&gt;; 发送时间:&nbsp;2024年5月9日(星期四) 晚上7:36 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [mikeqzy/3dgs-avatar-release] Error executing job with overrides: ['dataset=ps_female_3', 'option=iter30k', 'pose_correction=none'] (Issue #16) 我也遇到了这个问题，不知道你是否解决了 最近没在跑这个数据集 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
最近都在跑zju那个数据集，这个是没问题的。

**Comment by Mr-ind1fferent** [comment]
> 那不知道您是否有预处理好的数据集，不知道可不可以发我一份，如果可以的话，可以有偿，无论如何都感谢您的回答
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "mikeqzy/3dgs-avatar-release" ***@***.***&gt;; 发送时间:&nbsp;2024年5月9日(星期四) 晚上7:44 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [mikeqzy/3dgs-avatar-release] Error executing job with overrides: ['dataset=ps_female_3', 'option=iter30k', 'pose_correction=none'] (Issue #16) 您最终用的哪个数据集跑通的程序，我也试一试，您认为是数据集的问题还是说预处理有问题 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "mikeqzy/3dgs-avatar-release" @.&gt;; 发送时间:&nbsp;2024年5月9日(星期四) 晚上7:36 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [mikeqzy/3dgs-avatar-release] Error executing job with overrides: ['dataset=ps_female_3', 'option=iter30k', 'pose_correction=none'] (Issue #16) 我也遇到了这个问题，不知道你是否解决了 最近没在跑这个数据集 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt; 最近都在跑zju那个数据集，这个是没问题的。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

ZJU的数据集可以跑，ps的那个目前我也没处理

**Comment by jiangguangan** [comment]
ZJU那个处理的数据集可以麻烦您发我一份吗，我这个问题似乎就是处理后的数据集还是有一些问题，但我已经按照arah完整走了一遍，不胜感激




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mikeqzy/3dgs-avatar-release"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月9日(星期四) 晚上8:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mikeqzy/3dgs-avatar-release] Error executing job with overrides: ['dataset=ps_female_3', 'option=iter30k', 'pose_correction=none'] (Issue #16)





  
那不知道您是否有预处理好的数据集，不知道可不可以发我一份，如果可以的话，可以有偿，无论如何都感谢您的回答
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "mikeqzy/3dgs-avatar-release" @.&gt;; 发送时间:&nbsp;2024年5月9日(星期四) 晚上7:44 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [mikeqzy/3dgs-avatar-release] Error executing job with overrides: ['dataset=ps_female_3', 'option=iter30k', 'pose_correction=none'] (Issue #16) 您最终用的哪个数据集跑通的程序，我也试一试，您认为是数据集的问题还是说预处理有问题 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "mikeqzy/3dgs-avatar-release" @.&gt;; 发送时间:&nbsp;2024年5月9日(星期四) 晚上7:36 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [mikeqzy/3dgs-avatar-release] Error executing job with overrides: ['dataset=ps_female_3', 'option=iter30k', 'pose_correction=none'] (Issue #16) 我也遇到了这个问题，不知道你是否解决了 最近没在跑这个数据集 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.&gt; 最近都在跑zju那个数据集，这个是没问题的。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.&gt;
  
ZJU的数据集可以跑，ps的那个目前我也没处理

**Comment by Mr-ind1fferent** [comment]
> ZJU那个处理的数据集可以麻烦您发我一份吗，我这个问题似乎就是处理后的数据集还是有一些问题，但我已经按照arah完整走了一遍，不胜感激
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "mikeqzy/3dgs-avatar-release" ***@***.***&gt;; 发送时间:&nbsp;2024年5月9日(星期四) 晚上8:39 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [mikeqzy/3dgs-avatar-release] Error executing job with overrides: ['dataset=ps_female_3', 'option=iter30k', 'pose_correction=none'] (Issue #16) 那不知道您是否有预处理好的数据集，不知道可不可以发我一份，如果可以的话，可以有偿，无论如何都感谢您的回答 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "mikeqzy/3dgs-avatar-release" @.&gt;; 发送时间:&nbsp;2024年5月9日(星期四) 晚上7:44 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [mikeqzy/3dgs-avatar-release] Error executing job with overrides: ['dataset=ps_female_3', 'option=iter30k', 'pose_correction=none'] (Issue #16) 您最终用的哪个数据集跑通的程序，我也试一试，您认为是数据集的问题还是说预处理有问题 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "mikeqzy/3dgs-avatar-release" @.&gt;; 发送时间:&nbsp;2024年5月9日(星期四) 晚上7:36 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [mikeqzy/3dgs-avatar-release] Error executing job with overrides: ['dataset=ps_female_3', 'option=iter30k', 'pose_correction=none'] (Issue #16) 我也遇到了这个问题，不知道你是否解决了 最近没在跑这个数据集 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.&gt; 最近都在跑zju那个数据集，这个是没问题的。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.&gt; ZJU的数据集可以跑，ps的那个目前我也没处理 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

你看一下zju那个还有一个refine的版本，你看看有没有用错，直接就可以跑的

**Comment by jiangguangan** [comment]
因为我之前是使用的未经处理的zju，然后按照arah的预处理代码处理后遭遇了问题，请问refine的版本在哪里找，麻烦您发我一个链接，不胜感激。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mikeqzy/3dgs-avatar-release"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月9日(星期四) 晚上9:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mikeqzy/3dgs-avatar-release] Error executing job with overrides: ['dataset=ps_female_3', 'option=iter30k', 'pose_correction=none'] (Issue #16)





  
ZJU那个处理的数据集可以麻烦您发我一份吗，我这个问题似乎就是处理后的数据集还是有一些问题，但我已经按照arah完整走了一遍，不胜感激
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "mikeqzy/3dgs-avatar-release" @.&gt;; 发送时间:&nbsp;2024年5月9日(星期四) 晚上8:39 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [mikeqzy/3dgs-avatar-release] Error executing job with overrides: ['dataset=ps_female_3', 'option=iter30k', 'pose_correction=none'] (Issue #16) 那不知道您是否有预处理好的数据集，不知道可不可以发我一份，如果可以的话，可以有偿，无论如何都感谢您的回答 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "mikeqzy/3dgs-avatar-release" @.&gt;; 发送时间:&nbsp;2024年5月9日(星期四) 晚上7:44 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [mikeqzy/3dgs-avatar-release] Error executing job with overrides: ['dataset=ps_female_3', 'option=iter30k', 'pose_correction=none'] (Issue #16) 您最终用的哪个数据集跑通的程序，我也试一试，您认为是数据集的问题还是说预处理有问题 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "mikeqzy/3dgs-avatar-release" @.&gt;; 发送时间:&nbsp;2024年5月9日(星期四) 晚上7:36 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [mikeqzy/3dgs-avatar-release] Error executing job with overrides: ['dataset=ps_female_3', 'option=iter30k', 'pose_correction=none'] (Issue #16) 我也遇到了这个问题，不知道你是否解决了 最近没在跑这个数据集 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.&gt; 最近都在跑zju那个数据集，这个是没问题的。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.&gt; ZJU的数据集可以跑，ps的那个目前我也没处理 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
你看一下zju那个还有一个refine的版本，你看看有没有用错，直接就可以跑的

**Comment by mikeqzy** [comment]
> Thanks for your great work！
> 
> When i use python train.py dataset=ps_female_3 option=iter30k pose_correction=none
> 
> There is something wrong and i don't know how to fix it.
> 
> ![image](https://private-user-images.githubusercontent.com/74087260/320532758-6efcdfb0-0a32-4dcb-a22e-b0e6dd838294.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1ODA3NjIsIm5iZiI6MTcxNzU4MDQ2MiwicGF0aCI6Ii83NDA4NzI2MC8zMjA1MzI3NTgtNmVmY2RmYjAtMGEzMi00ZGNiLWEyMmUtYjBlNmRkODM4Mjk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDA5NDEwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0MGYyMjYzZjRjN2ZmMTRhM2Y3YWJlOWY4Nzk2ODFkZDdkYzU0N2Y3OGI2YmU2OWQwMzM4ZTIyNjllNTIxM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oR-GFd-BdgjMDHXAH9MQRqsC1DEvc0Jpof5znEkc5-s)

Hi, thank you for your interest. To run on the PeopleSnapshot dataset you'll need to preprocess it into arah-format. Unfortunately I could not find the preprocessing script, but it can easily adapted from https://github.com/taconite/arah-release/blob/main/preprocess_datasets/preprocess_ZJU-MoCap.py. Hope it helps!

**Comment by mikeqzy** [comment]
> 因为我之前是使用的未经处理的zju，然后按照arah的预处理代码处理后遭遇了问题，请问refine的版本在哪里找，麻烦您发我一个链接，不胜感激。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "mikeqzy/3dgs-avatar-release" ***@***.***&gt;; 发送时间:&nbsp;2024年5月9日(星期四) 晚上9:08 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [mikeqzy/3dgs-avatar-release] Error executing job with overrides: ['dataset=ps_female_3', 'option=iter30k', 'pose_correction=none'] (Issue #16) ZJU那个处理的数据集可以麻烦您发我一份吗，我这个问题似乎就是处理后的数据集还是有一些问题，但我已经按照arah完整走了一遍，不胜感激 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "mikeqzy/3dgs-avatar-release" @.&gt;; 发送时间:&nbsp;2024年5月9日(星期四) 晚上8:39 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [mikeqzy/3dgs-avatar-release] Error executing job with overrides: ['dataset=ps_female_3', 'option=iter30k', 'pose_correction=none'] (Issue #16) 那不知道您是否有预处理好的数据集，不知道可不可以发我一份，如果可以的话，可以有偿，无论如何都感谢您的回答 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "mikeqzy/3dgs-avatar-release" @.&gt;; 发送时间:&nbsp;2024年5月9日(星期四) 晚上7:44 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [mikeqzy/3dgs-avatar-release] Error executing job with overrides: ['dataset=ps_female_3', 'option=iter30k', 'pose_correction=none'] (Issue #16) 您最终用的哪个数据集跑通的程序，我也试一试，您认为是数据集的问题还是说预处理有问题 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "mikeqzy/3dgs-avatar-release" @.&gt;; 发送时间:&nbsp;2024年5月9日(星期四) 晚上7:36 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [mikeqzy/3dgs-avatar-release] Error executing job with overrides: ['dataset=ps_female_3', 'option=iter30k', 'pose_correction=none'] (Issue #16) 我也遇到了这个问题，不知道你是否解决了 最近没在跑这个数据集 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.&gt; 最近都在跑zju那个数据集，这个是没问题的。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.&gt; ZJU的数据集可以跑，ps的那个目前我也没处理 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt; 你看一下zju那个还有一个refine的版本，你看看有没有用错，直接就可以跑的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

你好，NeuralBody版本的ZJU-MoCap和refine后的ZJU-MoCap都可以跑。refine后的ZJU-MoCap请联系Instant-NVR的原作者获取：https://github.com/zju3dv/instant-nvr/blob/master/docs/install.md#set-up-datasets
