### ISSUE TITLE
How to generate ply files after training and rendering

### ISSUE THREAD

**Issue by Mr-ind1fferent** [mikeqzy/3dgs-avatar-release#18]
Thanks for the amazing work, but how can i obtain ply files.

**Comment by mikeqzy** [comment]
Hi, you can find the `save_ply` method from original 3DGS here: https://github.com/mikeqzy/3dgs-avatar-release/blob/6f57deb6fbd3ad929ce81ab61da8c4e056a5cedd/scene/gaussian_model.py#L248
However there are several points to note:
1. `f_dc` and `f_rest` is not used, since we use MLP instead of spherical harmonics to decode color.
2. `rotation` is not correct since the rotation after skinning is not converted back to quaternion, see [here](https://github.com/mikeqzy/3dgs-avatar-release/blob/6f57deb6fbd3ad929ce81ab61da8c4e056a5cedd/models/deformer/rigid.py#L233). You could convert it back to quaternion before storing to ply.
