### ISSUE TITLE
some question about rendering

### ISSUE THREAD

**Issue by liubc-ai** [mikeqzy/3dgs-avatar-release#27]
When I train on custom datasets and try to render in novel poses, I got the deformed point cloud in novel pose correctly, but rendering image is all black. 
![image](https://github.com/user-attachments/assets/cdbd0df0-110d-40e9-b8db-513040ca719f)
![image](https://github.com/user-attachments/assets/feb05e4f-f4e3-4c93-999f-a8f1958fe511)
When I debug the codes, I found rendered_image, radii is all zero after rasterizer:
![image](https://github.com/user-attachments/assets/627f2b68-576f-40b6-89c2-a245969d247f)

Could you please help me to solve this render question?
Thanks

**Comment by mikeqzy** [comment]
I would suspect the camera is wrong, could you quickly check if the projected 3D Gaussians fall inside the image?

**Comment by liubc-ai** [comment]
Thank you for your reply, the camera is wrong. 
I train on custom data processed by ROMP, but use aist_demo.npz  to render novel animations, which may be wrong. When I replace another motion sequence processed by ROMP， everything's ok.
But I still have some questions about subsequent optimization:
1. The limbs in the rendered image are very bad, whether this is related to the video used for traininng.(The custom video I use is a rotating T-pose, about 400 frames, rotated twice) The input video lacks joint movement of the arms and legs, could this be the cause of poor joint movement in rendering novel motion ?
![image](https://github.com/user-attachments/assets/9a226300-d2a6-4bf9-a52d-f996333ed46a)

2. I found using pose_correction can lead to more detailed face and more detailed texture in training sequence, but it doesn't do well when rendering novel movements. Is this because the pose_correction only learned the SMPL embedding of the training sequence ? 

![image](https://github.com/user-attachments/assets/98b33dc7-8184-4702-9515-b89bdce9826f)

What can I improve to make it generalize better for novel motion sequences ?

**Comment by mikeqzy** [comment]
1. In your case where the training video only includes T-pose, it is expected that the model will show poors generalization to novel poses. I also observe similar results for novel pose animation on PeopleSnapshot, where the training data is also a rotating sequence with highly limited pose variation. In such scenerios, the non-rigid deformation module would not make sense and I suggest trying to turn it off.
2. Yes, the pose correction module only optimizes the SMPL parameters of the training sequence. It has nothing to do with animation since the motion sequence to drive the avatar is provided by the user.

**Comment by liubc-ai** [comment]
I get it. 
Thank you for your kind reply!
