### ISSUE TITLE
Ply file issue

### ISSUE THREAD

**Issue by auideaslab** [mikeqzy/3dgs-avatar-release#5]
Hello. I have an issue with the ply file. It seems that rotations and scale values for each gaussians are wrong. You can easily verify that by disabling "compute covariance" when sending to renderer. If you compute covariance, render is correct. If you let renderer compute covariance from scaling and rotation, the rendering is wrong.

**Comment by mikeqzy** [comment]
Hi,
Yes, your observation is correct. The scale in the ply file is correct while the rotation (quaternion) is wrong.
The reason for this is, I directly store the rotation matrix for the deformed Gaussians after skinning [here](https://github.com/mikeqzy/3dgs-avatar-release/blob/main/models/deformer/rigid.py#L233). Since the forward transformation matrix is linearly blended by skinning weights, it does not necessarily form a valid rotation matrix. Thus, storing it as quaternion would require additional computation and possibly have numerical error. You could use `self.rotation_precomp` as the correct rotation matrix, or you could still store the quaternion by uncommenting [this](https://github.com/mikeqzy/3dgs-avatar-release/blob/main/models/deformer/rigid.py#L235). Hope this helps!
